let fruits = ["apple", "fraise", "mangue"];
fruits.push("orange");
console.log(fruits);
fruits.unshift("kiwi");
console.log(fruits);
fruits.splice(1, 0, "banane", "poire");
console.log(fruits);
fruits.splice(1, 1);
console.log(fruits);
fruits.shift();
console.log(fruits);
fruits.pop();
console.log(fruits);
fruits.sort();
console.log(fruits);
fruits.reverse();
console.log(fruits);
const fruitswitha = fruits.filter((fruit) => fruit.includes("a"));
console.log(fruitswitha);
const majusculeFruits = fruits.map((fruit) => fruit.toUpperCase());
console.log(majusculeFruits);
const hasBanane = fruits.some((fruit) => fruit === "apple");
console.log(hasBanane);
const allFruits = fruits.every((fruit) => fruit === "banane");
console.log(allFruits);
const maFraise = fruits.find((fruit) => fruit === "fraise");
console.log(maFraise);
const indexOfFraise = fruits.indexOf("fraise");
console.log(indexOfFraise);
fruits.forEach((fruit) => console.log(fruit));
const fruitsString = fruits.includes("figue ");
console.log(fruitsString);
const younesfruits = ["kiwi", "banane", "poire"];
const sofiefruits = ["fraise", "mangue", "orange"];
const lovedfruit = younesfruits.concat(sofiefruits);
console.log(lovedfruit);
const fruitsw = [...younesfruits, ...sofiefruits];
console.log(fruitsw);
